name: Deploy to cloudtype

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pleahmacaka/ait
          stage: main
          yaml: |
            name: front
            app: node@18
            options:
              env:
                - name: NODE_ENV
                  value: production
              ports: "4173"
              build: npm run build
              start: npm run preview -- --host
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}